/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lms.connection.ProvideConnection;

/**
 *
 * @author DELL
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public int user_id;

    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public AdminDashboard(int user_id) {
        initComponents();
        this.user_id = user_id;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        managecourseBtn = new javax.swing.JButton();
        managelecturerBtn = new javax.swing.JButton();
        managestudentBtn = new javax.swing.JButton();
        managetimetableBtn = new javax.swing.JButton();
        viewattendanceBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cancelBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tutorTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        courseTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tutorTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Admin Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(56, 69, 173));

        homeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/work-from-home.png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        managecourseBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        managecourseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/online-learning.png"))); // NOI18N
        managecourseBtn.setText("Manage Course");
        managecourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managecourseBtnActionPerformed(evt);
            }
        });

        managelecturerBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        managelecturerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/teacher.png"))); // NOI18N
        managelecturerBtn.setText("Manage Tutor");
        managelecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managelecturerBtnActionPerformed(evt);
            }
        });

        managestudentBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        managestudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/student.png"))); // NOI18N
        managestudentBtn.setText("Manage Student");
        managestudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managestudentBtnActionPerformed(evt);
            }
        });

        managetimetableBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        managetimetableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/calendar.png"))); // NOI18N
        managetimetableBtn.setText("Manage Time-table");
        managetimetableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managetimetableBtnActionPerformed(evt);
            }
        });

        viewattendanceBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        viewattendanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/attendant-list.png"))); // NOI18N
        viewattendanceBtn.setText("View Attendance");
        viewattendanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewattendanceBtnActionPerformed(evt);
            }
        });

        profileBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/profile.png"))); // NOI18N
        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/log-out.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/assign.png"))); // NOI18N
        jButton3.setText("Assign Tutor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(viewattendanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(managetimetableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(managestudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(managelecturerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(managecourseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(managecourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(managelecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(managestudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(managetimetableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(viewattendanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1556, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 68, 1181, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Total Tutors:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 99, -1, -1));

        tutorTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(tutorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 96, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Total Students:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 99, -1, -1));

        studentTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(studentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 96, 100, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Total Courses:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1255, 99, -1, -1));

        courseTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(courseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1426, 96, 100, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Course"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 152, 369, 735));

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Name"
            }
        ));
        jScrollPane2.setViewportView(courseTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 152, 369, 735));

        tutorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutor ID", "Tutor Name"
            }
        ));
        jScrollPane3.setViewportView(tutorTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 152, 369, 735));

        jPanel2.setBackground(new java.awt.Color(249, 244, 241));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void managecourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managecourseBtnActionPerformed
        // TODO add your handling code here:
        new ManageCourse().setVisible(true);
    }//GEN-LAST:event_managecourseBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        new AdminProfile(user_id).setVisible(true);

    }//GEN-LAST:event_profileBtnActionPerformed

    private void managelecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managelecturerBtnActionPerformed
        // TODO add your handling code here:
        new ManageTutor().setVisible(true);
    }//GEN-LAST:event_managelecturerBtnActionPerformed

    private void managestudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managestudentBtnActionPerformed
        // TODO add your handling code here:\\
        new ManageStudent().setVisible(true);
    }//GEN-LAST:event_managestudentBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new AssignTutor().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewattendanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewattendanceBtnActionPerformed
        // TODO add your handling code here:
        new ViewAttendance().setVisible(true);
    }//GEN-LAST:event_viewattendanceBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String countQueryTutor = "SELECT COUNT(*) AS total_tutors FROM tutor";
        String dataQueryTutor = "SELECT tutor_id, first_name FROM tutor";

        String countQueryStudent = "SELECT COUNT(*) AS total_students FROM student";
        String dataQueryStudent = "SELECT first_name, course FROM student";

        String countQueryCourse = "SELECT COUNT(*) AS total_courses FROM course";
        String dataQueryCourse = "SELECT course_id, course_name FROM course";

        try (Connection conn = ProvideConnection.getConnection();
                PreparedStatement countStmtTutor = conn.prepareStatement(countQueryTutor);
                PreparedStatement dataStmtTutor = conn.prepareStatement(dataQueryTutor);
                PreparedStatement countStmtStudent = conn.prepareStatement(countQueryStudent);
                PreparedStatement dataStmtStudent = conn.prepareStatement(dataQueryStudent);
                PreparedStatement countStmtCourse = conn.prepareStatement(countQueryCourse);
                PreparedStatement dataStmtCourse = conn.prepareStatement(dataQueryCourse);
                ResultSet countRsTutor = countStmtTutor.executeQuery();
                ResultSet dataRsTutor = dataStmtTutor.executeQuery();
                ResultSet countRsStudent = countStmtStudent.executeQuery();
                ResultSet dataRsStudent = dataStmtStudent.executeQuery();
                ResultSet countRsCourse = countStmtCourse.executeQuery();
                ResultSet dataRsCourse = dataStmtCourse.executeQuery()) {

            // Retrieve the total number of tutors
            if (countRsTutor.next()) {
                int totalTutors = countRsTutor.getInt("total_tutors");
                tutorTxt.setText(String.valueOf(totalTutors));
            }

            // Retrieve tutor_id and first_name and populate the JTable
            DefaultTableModel tutorModel = (DefaultTableModel) tutorTable.getModel();
            tutorModel.setRowCount(0); // Clear existing rows
            tutorModel.setColumnIdentifiers(new String[]{"Tutor ID", "First Name"}); // Set column names

            while (dataRsTutor.next()) {
                int tutorId = dataRsTutor.getInt("tutor_id");
                String firstName = dataRsTutor.getString("first_name");
                tutorModel.addRow(new Object[]{tutorId, firstName});
            }

            // Retrieve the total number of students
            if (countRsStudent.next()) {
                int totalStudents = countRsStudent.getInt(1); // Use column index
                studentTxt.setText(String.valueOf(totalStudents));
            }

            // Retrieve first_name and course and populate the JTable
            DefaultTableModel studentModel = (DefaultTableModel) studentTable.getModel();
            studentModel.setRowCount(0); // Clear existing rows
            studentModel.setColumnIdentifiers(new String[]{"First Name", "Course"}); // Set column names

            while (dataRsStudent.next()) {
                String firstName = dataRsStudent.getString("first_name");
                String courseName = dataRsStudent.getString("course");
                studentModel.addRow(new Object[]{firstName, courseName});
            }

            // Retrieve the total number of courses
            if (countRsCourse.next()) {
                int totalCourses = countRsCourse.getInt(1); // Use column index
                courseTxt.setText(String.valueOf(totalCourses));
            }

            // Retrieve course_id and course_name and populate the JTable
            DefaultTableModel courseModel = (DefaultTableModel) courseTable.getModel();
            courseModel.setRowCount(0); // Clear existing rows
            courseModel.setColumnIdentifiers(new String[]{"Course ID", "Course Name"}); // Set column names

            while (dataRsCourse.next()) {
                int courseId = dataRsCourse.getInt("course_id");
                String courseName = dataRsCourse.getString("course_name");
                courseModel.addRow(new Object[]{courseId, courseName});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void managetimetableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managetimetableBtnActionPerformed
        // TODO add your handling code here:
        new ManageTimetable().setVisible(true);
    }//GEN-LAST:event_managetimetableBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JTable courseTable;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton managecourseBtn;
    private javax.swing.JButton managelecturerBtn;
    private javax.swing.JButton managestudentBtn;
    private javax.swing.JButton managetimetableBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField studentTxt;
    private javax.swing.JTable tutorTable;
    private javax.swing.JTextField tutorTxt;
    private javax.swing.JButton viewattendanceBtn;
    // End of variables declaration//GEN-END:variables
}
