/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import lms.connection.ProvideConnection;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class ManageCourse extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourse
     */
    public String numberPattern = "^[0-9]*$";

    public ManageCourse() {
        initComponents();
        setLocation(560, 60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        courseidTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        coursenameLbl = new javax.swing.JLabel();
        coursenameTxt = new javax.swing.JTextField();
        feeLbl = new javax.swing.JLabel();
        credithourLbl = new javax.swing.JLabel();
        feeTxt = new javax.swing.JTextField();
        credithourTxt = new javax.swing.JTextField();
        courseidLbl = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchcourseTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Course");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(249, 244, 241));

        courseidTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        courseidTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseidTxtActionPerformed(evt);
            }
        });

        statusLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        statusLbl.setText("Status");

        coursenameLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        coursenameLbl.setText("Course Name");

        coursenameTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        coursenameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursenameTxtActionPerformed(evt);
            }
        });

        feeLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        feeLbl.setText("Fee");

        credithourLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        credithourLbl.setText("Credit Hour/s");

        feeTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        credithourTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        credithourTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credithourTxtActionPerformed(evt);
            }
        });

        courseidLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        courseidLbl.setText("Course ID");

        statusCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        statusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(credithourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(credithourTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coursenameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(coursenameTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(courseidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(courseidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(feeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(feeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursenameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coursenameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credithourLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credithourTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        jPanel2.setBackground(new java.awt.Color(56, 69, 173));

        addBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/updating.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/reset.png"))); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 63, -1, -1));

        courseTbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        courseTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Id", "Course Name", "Credit Hour/s", "Status", "Fee", "Created Date", "Modified Date"
            }
        ));
        courseTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courseTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 475, 1176, 412));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/loupe.png"))); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 426, 100, -1));

        searchcourseTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        searchcourseTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcourseTxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchcourseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 426, 300, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 1200, 10));

        jPanel3.setBackground(new java.awt.Color(249, 244, 241));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void credithourTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credithourTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credithourTxtActionPerformed

    private void statusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboActionPerformed

    private void courseidTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseidTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseidTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String course_id = courseidTxt.getText();
        String course_name = coursenameTxt.getText();
        String credit_hours = credithourTxt.getText();
        String status = (String) statusCombo.getSelectedItem();
        String fee = feeTxt.getText();

        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = today.format(formatter);
        System.out.println(formattedDate);

        if (course_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Course Name field is required.");
        } else if (credit_hours.equals("")) {
            JOptionPane.showMessageDialog(null, "Credit Hour/s field is required.");
        } else if (fee.equals("")) {
            JOptionPane.showMessageDialog(null, "Fee field is required.");
        } else {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE course SET course_name = ?, credit_hours = ?, status = ?, fee = ?, modified_date = ? WHERE course_id = ?;");
                ps.setInt(6, Integer.parseInt(course_id));
                ps.setString(1, course_name);
                ps.setInt(2, Integer.parseInt(credit_hours));
                ps.setString(3, status);
                ps.setFloat(4, Float.parseFloat(fee));
                ps.setString(5, formattedDate);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Course Updated Successfully.");
                setVisible(false);
                new ManageCourse().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void coursenameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursenameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursenameTxtActionPerformed

    private void searchcourseTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcourseTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchcourseTxtActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        courseidTxt.setText("");
        coursenameTxt.setText("");
        credithourTxt.setText("");
        statusCombo.removeAllItems();
        statusCombo.addItem("Active");
        statusCombo.addItem("Inactive");
        feeTxt.setText("");

    }//GEN-LAST:event_resetBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String course_id = courseidTxt.getText();
        String course_name = coursenameTxt.getText();
        String credit_hours = credithourTxt.getText();

        String status = (String) statusCombo.getSelectedItem();
        String fee = feeTxt.getText();

        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = today.format(formatter);
        System.out.println(formattedDate);

        if (course_id.equals("")) {
            JOptionPane.showMessageDialog(null, "Course Id field is required.");
        } else if (course_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Course Name field is required.");
        } else if (credit_hours.equals("")) {
            JOptionPane.showMessageDialog(null, "Credit Hour/s field is required.");
        } else if (fee.equals("")) {
            JOptionPane.showMessageDialog(null, "Fee field is required.");
        } else {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO course(course_id,course_name,credit_hours,status,fee,created_date,modified_date) VALUES(?,?,?,?,?,?,?)");
                ps.setInt(1, Integer.parseInt(course_id));
                ps.setString(2, course_name);
                ps.setInt(3, Integer.parseInt(credit_hours));
                ps.setString(4, status);
                ps.setInt(5, Integer.parseInt(fee));
                ps.setString(6, formattedDate);
                ps.setString(7, formattedDate);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Course Added Successfully.");
                setVisible(false);
                new ManageCourse().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) courseTbl.getModel();
        try {
            Connection con = ProvideConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM course");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("course_id"), rs.getString("course_name"), rs.getInt("credit_hours"), rs.getString("status"), rs.getFloat("fee"), rs.getString("created_date"), rs.getString("modified_date")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void courseTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseTblMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int index = courseTbl.getSelectedRow();
        TableModel model = courseTbl.getModel();
        String courseId = model.getValueAt(index, 0).toString();
        try {
            Connection con = ProvideConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM course where course_id=?");
            ps.setString(1, courseId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                courseidTxt.setText("" + rs.getInt("course_id"));
                coursenameTxt.setText(rs.getString("course_name"));
                credithourTxt.setText("" + rs.getInt("credit_hours"));
                String status = rs.getString("status");
                if (status.endsWith("Active")) {
                    statusCombo.removeAllItems();
                    statusCombo.addItem("Active");
                    statusCombo.addItem("Inactive");
                } else {
                    statusCombo.removeAllItems();
                    statusCombo.addItem("Inactive");
                    statusCombo.addItem("Active");
                }
                feeTxt.setText("" + rs.getFloat("fee"));
            }
            courseidTxt.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_courseTblMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String courseId = courseidTxt.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this course?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM course where course_id=?");
                ps.setString(1, courseId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Course  deleted succesfully.");
                setVisible(false);
                new ManageCourse().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JTable courseTbl;
    private javax.swing.JLabel courseidLbl;
    private javax.swing.JTextField courseidTxt;
    private javax.swing.JLabel coursenameLbl;
    private javax.swing.JTextField coursenameTxt;
    private javax.swing.JLabel credithourLbl;
    private javax.swing.JTextField credithourTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel feeLbl;
    private javax.swing.JTextField feeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField searchcourseTxt;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
