/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lms.connection.ProvideConnection;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class ManageStudent extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudent
     */
    public String mobileNumberPattern = "^[0-9]*$";

    public ManageStudent() {
        initComponents();
        setLocation(560, 60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studentidTxt = new javax.swing.JTextField();
        firstnameTxt = new javax.swing.JTextField();
        lastnameTxt = new javax.swing.JTextField();
        dobDate = new com.toedter.calendar.JDateChooser();
        enrolledDate = new com.toedter.calendar.JDateChooser();
        courseCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        addBtn2 = new javax.swing.JButton();
        updateBtn2 = new javax.swing.JButton();
        deleteBtn2 = new javax.swing.JButton();
        resetBtn2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchstudentTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTbl = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Student Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, 100, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 166, 100, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 232, 100, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Date of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 169, 100, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Course");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 234, 100, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Enrolled Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 100, 35));
        getContentPane().add(studentidTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 101, 300, 35));

        firstnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(firstnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 167, 300, 35));
        getContentPane().add(lastnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 233, 300, 35));
        getContentPane().add(dobDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 169, 300, 35));
        getContentPane().add(enrolledDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 300, 300, 35));

        courseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        getContentPane().add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 235, 300, 35));

        jPanel4.setBackground(new java.awt.Color(56, 69, 173));

        addBtn2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/add.png"))); // NOI18N
        addBtn2.setText("Add");
        addBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn2ActionPerformed(evt);
            }
        });

        updateBtn2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        updateBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/updating.png"))); // NOI18N
        updateBtn2.setText("Update");
        updateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn2ActionPerformed(evt);
            }
        });

        deleteBtn2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/delete.png"))); // NOI18N
        deleteBtn2.setText("Delete");
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });

        resetBtn2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        resetBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/reset.png"))); // NOI18N
        resetBtn2.setText("Reset");
        resetBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(updateBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(resetBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 72, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/loupe.png"))); // NOI18N
        jLabel8.setText("Search");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 442, -1, -1));

        searchstudentTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        searchstudentTxt.setText("ID or Name");
        searchstudentTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchstudentTxtMouseClicked(evt);
            }
        });
        searchstudentTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchstudentTxtActionPerformed(evt);
            }
        });
        searchstudentTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchstudentTxtKeyReleased(evt);
            }
        });
        getContentPane().add(searchstudentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 442, 300, -1));

        studentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "First Name", "Last Name", "Address", "Phone Number", "Date of Birth", "Course", "Enrolled Date"
            }
        ));
        studentTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 486, 1176, 409));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1200, 7));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 299, 100, 35));
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 300, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Phone Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 100, 35));
        getContentPane().add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 101, 300, 35));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(249, 244, 241));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        try {
            Connection con = ProvideConnection.getConnection();
            String coursename_query = "SELECT course_name FROM course";
            String query = "SELECT * FROM student";
            PreparedStatement preparedStatement1 = con.prepareStatement(coursename_query);
            ResultSet resultSet = preparedStatement1.executeQuery();
            PreparedStatement preparedStatement2 = con.prepareStatement(query);
            ResultSet rs = preparedStatement2.executeQuery();
            while (resultSet.next()) {
                courseCombo.addItem(resultSet.getString("course_name"));
            }
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("student_id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("address"), rs.getString("phone_number"), rs.getDate("date_of_birth"), rs.getString("course"), rs.getDate("enrolled_date")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void addBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn2ActionPerformed
        //        // TODO add your handling code here:
        String student_id = studentidTxt.getText();
        String first_name = firstnameTxt.getText();
        String last_name = lastnameTxt.getText();
        String address = addressTxt.getText();
        String phone_number = phoneTxt.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date_of_birth = dobDate.getDate();
        Date enrolled_Date = enrolledDate.getDate();
        String course = (String) courseCombo.getSelectedItem();
        String dob = "";
        String enrolldate = "";
        if (date_of_birth != null) {
            dob = dFormat.format(date_of_birth.getDate());
        }
        if (enrolled_Date != null) {
            enrolldate = dFormat.format(enrolled_Date.getDate());
        }

        if (student_id.equals("")) {
            JOptionPane.showMessageDialog(null, "Student Id field is required.");
        } else if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name field is required.");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name field is required.");
        } else if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address field is required.");
        } else if (phone_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number field is required.");
        } else if (!phone_number.matches(mobileNumberPattern) || phone_number.length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number filed is invalid.");
        } else if (dob.equals("")) {
            JOptionPane.showMessageDialog(null, "Date of birth field is required.");
        } else if (enrolldate.equals("")) {
            JOptionPane.showMessageDialog(null, "Enrolled Date field is required.");
        } else {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT INTO student(student_id, first_name, last_name, date_of_birth, phone_number, address, course, enrolled_date) VALUES(?,?,?,?,?,?,?,?)");
                ps.setInt(1, Integer.parseInt(student_id));
                ps.setString(2, first_name);
                ps.setString(3, last_name);
                ps.setDate(4, new java.sql.Date(date_of_birth.getTime()));
                ps.setString(5, phone_number);
                ps.setString(6, address);
                ps.setString(7, course);
                ps.setDate(8, new java.sql.Date(enrolled_Date.getTime()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student Added Successfully.");
                setVisible(false);
                new ManageStudent().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_addBtn2ActionPerformed

    private void updateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn2ActionPerformed
        //        // TODO add your handling code here:
        String student_id = studentidTxt.getText();
        String first_name = firstnameTxt.getText();
        String last_name = lastnameTxt.getText();
        String address = addressTxt.getText();
        String phone_number = phoneTxt.getText();
        Date dob = dobDate.getDate();
        String course = (String) courseCombo.getSelectedItem();
        Date enroll = enrolledDate.getDate();
        if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name field is required.");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name field is required.");
        } else if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "Address field is required.");
        } else if (phone_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number field is required.");
        } else if (!phone_number.matches(mobileNumberPattern) || phone_number.length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number filed is invalid.");
        } else if (course.equals("")) {
            JOptionPane.showMessageDialog(null, "Course field is required.");
        } else {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE student SET first_name=?,last_name=?,  date_of_birth=?, phone_number=?, address=?, course=?, enrolled_date=? WHERE student_id=?");
                ps.setInt(8, Integer.parseInt(student_id));
                ps.setString(1, first_name);
                ps.setString(2, last_name);
                ps.setDate(3, new java.sql.Date(dob.getTime()));
                ps.setString(4, phone_number);
                ps.setString(5, address);
                ps.setString(6, course);
                ps.setDate(7, new java.sql.Date(enroll.getTime()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student Updated Successfully.");
                setVisible(false);
                new ManageStudent().setVisible(true);
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_updateBtn2ActionPerformed

    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        // TODO add your handling code here:
        String studentId = studentidTxt.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this Student?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM student where student_id=?");
                ps.setString(1, studentId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student deleted succesfully.");
                setVisible(false);
                new ManageStudent().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void resetBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtn2ActionPerformed
        // TODO add your handling code here:
        studentidTxt.setText("");
        studentidTxt.setEditable(true);
        firstnameTxt.setText("");
        lastnameTxt.setText("");
        addressTxt.setText("");
        dobDate.setDate(null);
        enrolledDate.setDate(null);
        phoneTxt.setText("");
        courseCombo.setSelectedIndex(0);
    }//GEN-LAST:event_resetBtn2ActionPerformed

    private void firstnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtActionPerformed

    private void searchstudentTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchstudentTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchstudentTxtActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboActionPerformed

    private void studentTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTblMouseClicked
        // TODO add your handling code here:
        int index = studentTbl.getSelectedRow();
        TableModel model = studentTbl.getModel();
        String studentId = model.getValueAt(index, 0).toString();
        try {
            Connection con = ProvideConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM student where student_id=?");
            ps.setString(1, studentId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                studentidTxt.setText("" + rs.getInt("student_id"));
                firstnameTxt.setText(rs.getString("first_name"));
                lastnameTxt.setText(rs.getString("last_name"));
                addressTxt.setText(rs.getString("address"));
                phoneTxt.setText(rs.getString("phone_number"));
                addressTxt.setText(rs.getString("address"));
                dobDate.setDate(rs.getDate("date_of_birth"));
                courseCombo.setSelectedItem(rs.getString("course"));
                enrolledDate.setDate(rs.getDate("enrolled_date"));
            }
            studentidTxt.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_studentTblMouseClicked

    private void searchstudentTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchstudentTxtKeyReleased
        // TODO add your handling code here:
        String search = searchstudentTxt.getText();
        studentSearch(search);
    }//GEN-LAST:event_searchstudentTxtKeyReleased

    private void searchstudentTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchstudentTxtMouseClicked
        // TODO add your handling code here:
        searchstudentTxt.setText("");
    }//GEN-LAST:event_searchstudentTxtMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    public void studentSearch(String search) {
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        model.setRowCount(0);
        try {
            Connection con = ProvideConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM student WHERE first_name LIKE '" + search + "%' OR student_id LIKE '" + search + "%'");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("student_id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("address"), rs.getString("phone_number"), rs.getDate("date_of_birth"), rs.getString("course"), rs.getDate("enrolled_date")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn2;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JButton deleteBtn2;
    private com.toedter.calendar.JDateChooser dobDate;
    private com.toedter.calendar.JDateChooser enrolledDate;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton resetBtn2;
    private javax.swing.JTextField searchstudentTxt;
    private javax.swing.JTable studentTbl;
    private javax.swing.JTextField studentidTxt;
    private javax.swing.JButton updateBtn2;
    // End of variables declaration//GEN-END:variables
}
