/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lms.connection.ProvideConnection;

/**
 *
 * @author DELL
 */
public class ManageTutor extends javax.swing.JFrame {

    /**
     * Creates new form ManageTeacher
     */
    Connection con = ProvideConnection.getConnection();
    byte[] photo = null;
    String filename = null;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-z-A-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";

    public ManageTutor() {
        initComponents();
        setLocation(560, 60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturerTxt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tutoridTxt = new javax.swing.JTextField();
        addressLbl = new javax.swing.JLabel();
        firstnameLbl = new javax.swing.JLabel();
        firstnameTxt = new javax.swing.JTextField();
        feeLbl = new javax.swing.JLabel();
        lastnameLbl = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        lastnameTxt = new javax.swing.JTextField();
        lectureridLbl = new javax.swing.JLabel();
        searchtutorTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tutorTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        emailLbl = new javax.swing.JLabel();
        phonenumberLbl = new javax.swing.JLabel();
        phonenumberTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        photochooseBtn = new javax.swing.JButton();
        fileTxt = new javax.swing.JTextField();
        joineddateLb = new javax.swing.JLabel();
        joinedDate = new com.toedter.calendar.JDateChooser();
        emailLbl1 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lecturerTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lecturerTxt.setText("Tutor");
        getContentPane().add(lecturerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(249, 244, 241));

        tutoridTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        tutoridTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutoridTxtActionPerformed(evt);
            }
        });

        addressLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        addressLbl.setText("Address");

        firstnameLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        firstnameLbl.setText("First Name");

        firstnameTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        firstnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTxtActionPerformed(evt);
            }
        });

        feeLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        feeLbl.setText("Photo ");

        lastnameLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lastnameLbl.setText("Last Name");

        addressTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        lastnameTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lastnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTxtActionPerformed(evt);
            }
        });

        lectureridLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lectureridLbl.setText("Tutor ID");

        searchtutorTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        searchtutorTxt.setText("ID or Name");
        searchtutorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtutorTxtActionPerformed(evt);
            }
        });
        searchtutorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtutorTxtKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/loupe.png"))); // NOI18N
        jLabel2.setText("Search");

        tutorTbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tutorTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tutor Id", "First Name", "Last Name", "Email", "Phone Number", "Address", "Joined Date"
            }
        ));
        tutorTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tutorTbl);

        jPanel2.setBackground(new java.awt.Color(56, 69, 173));

        addBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/add.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/updating.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        resetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/reset.png"))); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        emailLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        emailLbl.setText("Email");

        phonenumberLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        phonenumberLbl.setText("Phone Number");

        phonenumberTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        phonenumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumberTxtActionPerformed(evt);
            }
        });

        emailTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        photochooseBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        photochooseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/gallery.png"))); // NOI18N
        photochooseBtn.setText("Choose Phtoto");
        photochooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photochooseBtnActionPerformed(evt);
            }
        });

        fileTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N

        joineddateLb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        joineddateLb.setText("Joined Date");

        emailLbl1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        emailLbl1.setText("Password");

        passwordTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lastnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lastnameTxt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(firstnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(firstnameTxt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lectureridLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tutoridTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(joineddateLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(feeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumberLbl))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phonenumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(joinedDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(photochooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(searchtutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lectureridLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tutoridTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(photochooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phonenumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(joineddateLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(feeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 83, -1, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1200, 10));

        jPanel3.setBackground(new java.awt.Color(249, 244, 241));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutoridTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutoridTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutoridTxtActionPerformed

    private void firstnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtActionPerformed

    private void lastnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
//        // TODO add your handling code here:
        String tutor_id = tutoridTxt.getText();
        String first_name = firstnameTxt.getText();
        String last_name = lastnameTxt.getText();
        String email = emailTxt.getText();
        String phone_number = phonenumberTxt.getText();
        String address = addressTxt.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date joined_Date = joinedDate.getDate();
        String jDate = "";
        if (joined_Date != null) {
            jDate = dFormat.format(joinedDate.getDate());
        }
        String password = passwordTxt.getText();
        if (tutor_id.equals("")) {
            JOptionPane.showMessageDialog(null, "Tutor Id field is required.");
        } else if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name field is required.");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name field is required.");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email field is required.");
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Email field is invalid.");
        } else if (phone_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number field is required.");
        } else if (!phone_number.matches(mobileNumberPattern) || phone_number.length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number filed is invalid.");
        } else {
            try {
                con.setAutoCommit(false);  // Start transaction
                // Insert into user_details first
                PreparedStatement ps_user = con.prepareStatement("INSERT INTO user_details(userName, passWord, email, phone_number, userRole) VALUES(?, ?, ?, ?, ?)", Statement.RETURN_GENERATED_KEYS);
                ps_user.setString(1, first_name);
                ps_user.setString(2, password);
                ps_user.setString(3, email);
                ps_user.setString(4, phone_number);
                ps_user.setString(5, "tutor");
                ps_user.executeUpdate();

                ResultSet rs = ps_user.getGeneratedKeys();
                int user_id_insert = 0;
                if (rs.next()) {
                    user_id_insert = rs.getInt(1);
                }

                // Now insert into tutor table using the new user_id
                PreparedStatement ps = con.prepareStatement("INSERT INTO tutor(tutor_id, userId, first_name, last_name, email, phone_number, address, joined_date, photo) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)");
                ps.setInt(1, Integer.parseInt(tutor_id));
                ps.setInt(2, user_id_insert);
                ps.setString(3, first_name);
                ps.setString(4, last_name);
                ps.setString(5, email);
                ps.setString(6, phone_number);
                ps.setString(7, address);
                ps.setDate(8, new java.sql.Date(joined_Date.getTime()));
                ps.setString(9, filename);
                ps.executeUpdate();

                con.commit();  // Commit transaction
                JOptionPane.showMessageDialog(null, "Tutor Added Successfully.");
                setVisible(false);
                new ManageTutor().setVisible(true);

                // Close resources
                rs.close();
                ps_user.close();
                ps.close();
                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                try {
                    if (con != null) {
                        con.rollback();  // Rollback transaction in case of error
                    }
                } catch (SQLException se) {
                    se.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
//        // TODO add your handling code here:
        String tutor_id = tutoridTxt.getText();
        String first_name = firstnameTxt.getText();
        String last_name = lastnameTxt.getText();
        String email = emailTxt.getText();
        String phone_number = phonenumberTxt.getText();
        String address = addressTxt.getText();
        filename = fileTxt.getText();
        if (first_name.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name field is required.");
        } else if (last_name.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name field is required.");
        } else if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Email field is required.");
        } else if (!email.matches(emailPattern)) {
            JOptionPane.showMessageDialog(null, "Email field is invalid.");
        } else if (phone_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number field is required.");
        } else if (!phone_number.matches(mobileNumberPattern) || phone_number.length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number filed is invalid.");
        } else {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("UPDATE tutor SET first_name=?,last_name=?,email=?,phone_number=?,address=?,photo=? WHERE tutor_id=?");
                ps.setString(1, first_name);
                ps.setString(2, last_name);
                ps.setString(3, email);
                ps.setString(4, phone_number);
                ps.setString(5, address);
                ps.setString(6, filename);
                ps.setInt(7, Integer.parseInt(tutor_id));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Tutor Updates Successfully.");
                setVisible(false);
                new ManageTutor().setVisible(true);
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String courseId = tutoridTxt.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to delete this course?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            try {
                Connection con = ProvideConnection.getConnection();
                PreparedStatement ps = con.prepareStatement("DELETE FROM course where course_id=?");
                ps.setString(1, courseId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Course  deleted succesfully.");
                setVisible(false);
                new ManageCourse().setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        tutoridTxt.setText("");
        firstnameTxt.setText("");
        lastnameTxt.setText("");
        addressTxt.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void phonenumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumberTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void photochooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photochooseBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();
        filename = f.getAbsolutePath();
        fileTxt.setText(filename);

    }//GEN-LAST:event_photochooseBtnActionPerformed

    private void searchtutorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtutorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtutorTxtActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tutorTbl.getModel();
        try {
            Connection con = ProvideConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tutor");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("tutor_id"), rs.getString("first_name"), rs.getString("last_name"), rs.getString("email"), rs.getString("phone_number"), rs.getString("address"), rs.getDate("joined_date")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void tutorTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorTblMouseClicked
        // TODO add your handling code here:
        int index = tutorTbl.getSelectedRow();
        TableModel model = tutorTbl.getModel();
        String tutorId = model.getValueAt(index, 0).toString();
        try {
            Connection con = ProvideConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM tutor where tutor_id=?");
            ps.setString(1, tutorId);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                tutoridTxt.setText("" + rs.getInt("tutor_id"));
                firstnameTxt.setText(rs.getString("first_name"));
                lastnameTxt.setText(rs.getString("last_name"));
                emailTxt.setText(rs.getString("email"));
                phonenumberTxt.setText(rs.getString("phone_number"));
                addressTxt.setText(rs.getString("address"));
                joinedDate.setDate(rs.getDate("joined_date"));
                fileTxt.setText(rs.getString("photo"));
            }
            tutoridTxt.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tutorTblMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void searchtutorTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtutorTxtKeyReleased
        // TODO add your handling code here:
        searchtutorTxt.setText("");
        String search = searchtutorTxt.getText();
        searchTutor(search);
    }//GEN-LAST:event_searchtutorTxtKeyReleased

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    public void searchTutor(String search) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailLbl1;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel feeLbl;
    private javax.swing.JTextField fileTxt;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JTextField firstnameTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser joinedDate;
    private javax.swing.JLabel joineddateLb;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JTextField lastnameTxt;
    private javax.swing.JLabel lecturerTxt;
    private javax.swing.JLabel lectureridLbl;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel phonenumberLbl;
    private javax.swing.JTextField phonenumberTxt;
    private javax.swing.JButton photochooseBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField searchtutorTxt;
    private javax.swing.JTable tutorTbl;
    private javax.swing.JTextField tutoridTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
