/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lms.connection.ProvideConnection;

/**
 *
 * @author DELL
 */
public class TutorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TutorDashboard
     */
    public int tutor_id;
    public int user_id;

    public TutorDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public TutorDashboard(int tutor_id, int user_id) {
        initComponents();
        this.tutor_id = tutor_id;
        this.user_id = user_id;
        System.out.println(tutor_id);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        viewcourseBtn = new javax.swing.JButton();
        viewstudentBtn = new javax.swing.JButton();
        viewtimetableBtn = new javax.swing.JButton();
        viewattendanceBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        manageassignmentBtn = new javax.swing.JButton();
        markassignmentBtn = new javax.swing.JButton();
        manageattendanceBtn2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cancelBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        studentTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        assignmentTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        assignmentTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Tutor Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(56, 69, 173));

        homeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/work-from-home.png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        viewcourseBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        viewcourseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/online-learning.png"))); // NOI18N
        viewcourseBtn.setText("View Course");
        viewcourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcourseBtnActionPerformed(evt);
            }
        });

        viewstudentBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        viewstudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/student.png"))); // NOI18N
        viewstudentBtn.setText("View Student");
        viewstudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstudentBtnActionPerformed(evt);
            }
        });

        viewtimetableBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        viewtimetableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/schedule.png"))); // NOI18N
        viewtimetableBtn.setText("View Time-table");
        viewtimetableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtimetableBtnActionPerformed(evt);
            }
        });

        viewattendanceBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        viewattendanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/attendant-list.png"))); // NOI18N
        viewattendanceBtn.setText("View Attendance");
        viewattendanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewattendanceBtnActionPerformed(evt);
            }
        });

        profileBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/profile.png"))); // NOI18N
        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/log-out.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        manageassignmentBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        manageassignmentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/qa.png"))); // NOI18N
        manageassignmentBtn.setText("Manage Assignment");
        manageassignmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageassignmentBtnActionPerformed(evt);
            }
        });

        markassignmentBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        markassignmentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/mark.png"))); // NOI18N
        markassignmentBtn.setText("Mark Assignment");
        markassignmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markassignmentBtnActionPerformed(evt);
            }
        });

        manageattendanceBtn2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        manageattendanceBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/verified-account.png"))); // NOI18N
        manageattendanceBtn2.setText("Manage Attendance");
        manageattendanceBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageattendanceBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageattendanceBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(markassignmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageassignmentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(viewattendanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(viewtimetableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(viewstudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(viewcourseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(viewcourseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(viewstudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(viewtimetableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(manageassignmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(markassignmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(manageattendanceBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(viewattendanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 68, 1184, 10));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1556, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Total Students:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 86, -1, -1));

        studentTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(studentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 83, 100, -1));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Course"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 134, -1, 750));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Total Assignments:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 81, -1, -1));

        assignmentTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(assignmentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1273, 78, 100, -1));

        assignmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignment Id", "Assignment Name", "Assigned Date", "Submission Date"
            }
        ));
        jScrollPane2.setViewportView(assignmentTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 134, 700, 753));

        jPanel2.setBackground(new java.awt.Color(249, 244, 241));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1210, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void viewcourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcourseBtnActionPerformed
        // TODO add your handling code here:
        new ManageCourse().setVisible(true);
    }//GEN-LAST:event_viewcourseBtnActionPerformed

    private void viewstudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstudentBtnActionPerformed
        // TODO add your handling code here:\\
        new ViewStudent(tutor_id).setVisible(true);
    }//GEN-LAST:event_viewstudentBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        new Profile(user_id).setVisible(true);

    }//GEN-LAST:event_profileBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewtimetableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtimetableBtnActionPerformed
        // TODO add your handling code here:
        new ViewTimeTable(tutor_id).setVisible(true);
    }//GEN-LAST:event_viewtimetableBtnActionPerformed

    private void manageattendanceBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageattendanceBtn2ActionPerformed
        // TODO add your handling code here:
        new ManageAttendance(tutor_id).setVisible(true);
    }//GEN-LAST:event_manageattendanceBtn2ActionPerformed

    private void viewattendanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewattendanceBtnActionPerformed
        // TODO add your handling code here:
        new ViewAttendance(tutor_id).setVisible(true);
    }//GEN-LAST:event_viewattendanceBtnActionPerformed

    private void manageassignmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageassignmentBtnActionPerformed
        // TODO add your handling code here:
        new ManageAssignment(tutor_id).setVisible(true);
    }//GEN-LAST:event_manageassignmentBtnActionPerformed

    private void markassignmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markassignmentBtnActionPerformed
        // TODO add your handling code here:
        new MarkAssignment(tutor_id).setVisible(true);
    }//GEN-LAST:event_markassignmentBtnActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // SQL queries for students
        String countQueryStudent = "SELECT COUNT(*) AS total_students FROM student";
        String dataQueryStudent = "SELECT first_name, course FROM student";

        // SQL queries for assignments
        String countQueryAssignment = "SELECT COUNT(*) AS total_assignments FROM assignment";
        String dataQueryAssignment = "SELECT assignment_id, assignment, date, submission_date FROM assignment";

        try (Connection conn = ProvideConnection.getConnection();
                PreparedStatement countStmtStudent = conn.prepareStatement(countQueryStudent);
                PreparedStatement dataStmtStudent = conn.prepareStatement(dataQueryStudent);
                PreparedStatement countStmtAssignment = conn.prepareStatement(countQueryAssignment);
                PreparedStatement dataStmtAssignment = conn.prepareStatement(dataQueryAssignment);
                ResultSet countRsStudent = countStmtStudent.executeQuery();
                ResultSet dataRsStudent = dataStmtStudent.executeQuery();
                ResultSet countRsAssignment = countStmtAssignment.executeQuery();
                ResultSet dataRsAssignment = dataStmtAssignment.executeQuery()) {

            // Retrieve the total number of students
            if (countRsStudent.next()) {
                int totalStudents = countRsStudent.getInt(1); // Use column index
                studentTxt.setText(String.valueOf(totalStudents));
            }

            // Retrieve first_name and course and populate the JTable
            DefaultTableModel studentModel = (DefaultTableModel) studentTable.getModel();
            studentModel.setRowCount(0); // Clear existing rows
            studentModel.setColumnIdentifiers(new String[]{"First Name", "Course"}); // Set column names

            while (dataRsStudent.next()) {
                String firstName = dataRsStudent.getString("first_name");
                String courseName = dataRsStudent.getString("course");
                studentModel.addRow(new Object[]{firstName, courseName});
            }

            // Retrieve the total number of assignments
            if (countRsAssignment.next()) {
                int totalAssignments = countRsAssignment.getInt(1); // Use column index
                assignmentTxt.setText(String.valueOf(totalAssignments));
            }

            // Retrieve assignment_id, assignment, date, and submission_date and populate the JTable
            DefaultTableModel assignmentModel = (DefaultTableModel) assignmentTable.getModel();
            assignmentModel.setRowCount(0); // Clear existing rows
            assignmentModel.setColumnIdentifiers(new String[]{"Assignment ID", "Assignment", "Date", "Submission Date"}); // Set column names

            while (dataRsAssignment.next()) {
                int assignmentId = dataRsAssignment.getInt("assignment_id");
                String assignment = dataRsAssignment.getString("assignment");
                String date = dataRsAssignment.getString("date");
                String submissionDate = dataRsAssignment.getString("submission_date");
                assignmentModel.addRow(new Object[]{assignmentId, assignment, date, submissionDate});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assignmentTable;
    private javax.swing.JTextField assignmentTxt;
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageassignmentBtn;
    private javax.swing.JButton manageattendanceBtn2;
    private javax.swing.JButton markassignmentBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JTable studentTable;
    private javax.swing.JTextField studentTxt;
    private javax.swing.JButton viewattendanceBtn;
    private javax.swing.JButton viewcourseBtn;
    private javax.swing.JButton viewstudentBtn;
    private javax.swing.JButton viewtimetableBtn;
    // End of variables declaration//GEN-END:variables
}
