/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms.gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lms.connection.ProvideConnection;

/**
 *
 * @author DELL
 */
public class ViewStudent extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudent
     */
    public int tutor_id;

    public ViewStudent() {
        initComponents();
        setLocation(560, 60);
        totalstudentTxt.setText(""+0);
    }

    public ViewStudent(int tutor_id) {
        initComponents();
        this.tutor_id = tutor_id;
        setLocation(560, 60);
        totalstudentTxt.setText(""+0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        viewBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        totalstudentTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setText("View Student");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 13, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 1200, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel3.setText("Course Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 80, -1, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel4.setText("Search");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 82, -1, 35));

        searchTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        searchTxt.setText("Student Id or Name or Course name");
        searchTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtMouseClicked(evt);
            }
        });
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 82, 300, 35));

        courseCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        courseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        getContentPane().add(courseCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 80, 300, 35));

        viewBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        viewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/file.png"))); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 80, -1, -1));

        searchBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/loupe.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 80, -1, -1));

        studentTbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        studentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "First Name", "Last Name", "Date of birth", "Phone Number", "Address", "Course", "Enrolled Date"
            }
        ));
        jScrollPane1.setViewportView(studentTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, 1176, 682));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setText("Total Student");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 834, -1, 35));

        totalstudentTxt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        getContentPane().add(totalstudentTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 834, 200, 35));

        clearBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/eraser.png"))); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1069, 832, -1, -1));

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/images/cancel.png"))); // NOI18N
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 13, -1, -1));

        jPanel1.setBackground(new java.awt.Color(249, 244, 241));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void updateTotalStudentCount() {
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        int rowCount = model.getRowCount();
        totalstudentTxt.setText(String.valueOf(rowCount));
    }

    public List<String> getCourseNamesByTutorId(int tutorId) {
        List<String> courseNames = new ArrayList<>();

        String courseIdQuery = "SELECT course_id FROM assign_tutor WHERE tutor_id = ?";
        String courseNameQuery = "SELECT course_name FROM course WHERE course_id = ?";

        try {
            // Retrieve course IDs
            Connection con = ProvideConnection.getConnection();
            List<Integer> courseIds = new ArrayList<>();
            try (PreparedStatement courseIdStmt = con.prepareStatement(courseIdQuery)) {
                courseIdStmt.setInt(1, tutorId);
                try (ResultSet courseIdRs = courseIdStmt.executeQuery()) {
                    while (courseIdRs.next()) {
                        courseIds.add(courseIdRs.getInt("course_id"));
                    }
                }
            }

            // Retrieve course names for the obtained course IDs
            try (PreparedStatement courseNameStmt = con.prepareStatement(courseNameQuery)) {
                for (int courseId : courseIds) {
                    courseNameStmt.setInt(1, courseId);
                    try (ResultSet courseNameRs = courseNameStmt.executeQuery()) {
                        if (courseNameRs.next()) {
                            courseNames.add(courseNameRs.getString("course_name"));
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return courseNames;
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        List<String> courseNames = getCourseNamesByTutorId(tutor_id);
        for (String courseName : courseNames) {
            courseCombo.addItem(courseName);
        }
    }//GEN-LAST:event_formComponentShown

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        String selectedCourse = (String) courseCombo.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        model.setRowCount(0);
        if (selectedCourse == null || selectedCourse.equals("None")) {
            JOptionPane.showMessageDialog(null, "Please select course.");
        } else {
            Connection connection = ProvideConnection.getConnection();
            try {
                String query = "SELECT student_id, first_name, last_name, date_of_birth, phone_number, address, course, enrolled_date FROM student WHERE course = '" + selectedCourse + "'";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(query);

                while (resultSet.next()) {
                    Object[] row = new Object[8];
                    row[0] = resultSet.getString("student_id");
                    row[1] = resultSet.getString("first_name");
                    row[2] = resultSet.getString("last_name");
                    row[3] = resultSet.getDate("date_of_birth");
                    row[4] = resultSet.getString("phone_number");
                    row[5] = resultSet.getString("address");
                    row[6] = resultSet.getString("course");
                    row[7] = resultSet.getDate("enrolled_date");
                    model.addRow(row);
                }
                updateTotalStudentCount();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchValue = searchTxt.getText().trim();
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        model.setRowCount(0); // Clear existing rows

        if (searchValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a value to search.");
            return;
        }

        Connection connection = ProvideConnection.getConnection();
        try {
            // Search by student_id, first_name, or course
            String query = "SELECT student_id, first_name, last_name, date_of_birth, phone_number, address, course, enrolled_date FROM student WHERE student_id LIKE '%" + searchValue + "%' OR first_name LIKE '%" + searchValue + "%' OR course LIKE '%" + searchValue + "%'";
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery(query);

            while (resultSet.next()) {
                Object[] row = new Object[8];
                row[0] = resultSet.getString("student_id");
                row[1] = resultSet.getString("first_name");
                row[2] = resultSet.getString("last_name");
                row[3] = resultSet.getDate("date_of_birth");
                row[4] = resultSet.getString("phone_number");
                row[5] = resultSet.getString("address");
                row[6] = resultSet.getString("course");
                row[7] = resultSet.getDate("enrolled_date");
                model.addRow(row);
            }
            updateTotalStudentCount();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTxtMouseClicked
        // TODO add your handling code here:
        searchTxt.setText("");
    }//GEN-LAST:event_searchTxtMouseClicked

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) studentTbl.getModel();
        model.setRowCount(0);
        courseCombo.setSelectedItem("None");
        searchTxt.setText("Student Id or Name or Course name");
        updateTotalStudentCount();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable studentTbl;
    private javax.swing.JTextField totalstudentTxt;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
